
CFLAGS = -O2 -Wall -Wextra -Wmissing-prototypes -Wstrict-prototypes -Werror=implicit-function-declaration -Werror=missing-prototypes

armid : armid.c
	-rm armid
	cc -o armid armid.c

all: armid

.PHONY : all
clean :
	-rm armid
